2024-08-30 13:40:20,805 - sentence_transformers.SentenceTransformer - INFO - __init__ - 189- Use pytorch device_name: cpu
2024-08-30 13:40:20,806 - sentence_transformers.SentenceTransformer - INFO - __init__ - 197- Load pretrained SentenceTransformer: all-MiniLM-L6-v2
2024-08-30 13:46:26,239 - sentence_transformers.SentenceTransformer - INFO - __init__ - 189- Use pytorch device_name: cpu
2024-08-30 13:46:26,239 - sentence_transformers.SentenceTransformer - INFO - __init__ - 197- Load pretrained SentenceTransformer: all-MiniLM-L6-v2
2024-08-30 13:46:40,331 - sentence_transformers.SentenceTransformer - INFO - __init__ - 189- Use pytorch device_name: cpu
2024-08-30 13:46:40,332 - sentence_transformers.SentenceTransformer - INFO - __init__ - 197- Load pretrained SentenceTransformer: all-MiniLM-L6-v2
2024-08-30 13:50:34,521 - sentence_transformers.SentenceTransformer - INFO - __init__ - 189- Use pytorch device_name: cpu
2024-08-30 13:50:34,521 - sentence_transformers.SentenceTransformer - INFO - __init__ - 197- Load pretrained SentenceTransformer: all-MiniLM-L6-v2
2024-08-30 13:50:44,486 - sentence_transformers.SentenceTransformer - INFO - __init__ - 189- Use pytorch device_name: cpu
2024-08-30 13:50:44,486 - sentence_transformers.SentenceTransformer - INFO - __init__ - 197- Load pretrained SentenceTransformer: all-MiniLM-L6-v2
2024-08-30 13:51:55,759 - sentence_transformers.SentenceTransformer - INFO - __init__ - 189- Use pytorch device_name: cpu
2024-08-30 13:51:55,759 - sentence_transformers.SentenceTransformer - INFO - __init__ - 197- Load pretrained SentenceTransformer: all-MiniLM-L6-v2
2024-08-30 13:52:06,891 - sentence_transformers.SentenceTransformer - INFO - __init__ - 189- Use pytorch device_name: cpu
2024-08-30 13:52:06,891 - sentence_transformers.SentenceTransformer - INFO - __init__ - 197- Load pretrained SentenceTransformer: all-MiniLM-L6-v2
2024-08-30 17:17:23,104 - sentence_transformers.SentenceTransformer - INFO - __init__ - 189- Use pytorch device_name: cpu
2024-08-30 17:17:23,106 - sentence_transformers.SentenceTransformer - INFO - __init__ - 197- Load pretrained SentenceTransformer: all-MiniLM-L6-v2
2024-08-30 17:21:34,834 - sentence_transformers.SentenceTransformer - INFO - __init__ - 189- Use pytorch device_name: cpu
2024-08-30 17:21:34,834 - sentence_transformers.SentenceTransformer - INFO - __init__ - 197- Load pretrained SentenceTransformer: all-MiniLM-L6-v2
2024-08-30 17:25:28,747 - sentence_transformers.SentenceTransformer - INFO - __init__ - 189- Use pytorch device_name: cpu
2024-08-30 17:25:28,747 - sentence_transformers.SentenceTransformer - INFO - __init__ - 197- Load pretrained SentenceTransformer: all-MiniLM-L6-v2
2024-08-30 17:25:40,788 - sentence_transformers.SentenceTransformer - INFO - __init__ - 189- Use pytorch device_name: cpu
2024-08-30 17:25:40,788 - sentence_transformers.SentenceTransformer - INFO - __init__ - 197- Load pretrained SentenceTransformer: all-MiniLM-L6-v2
2024-08-30 20:33:16,951 - sentence_transformers.SentenceTransformer - INFO - __init__ - 189- Use pytorch device_name: cpu
2024-08-30 20:33:16,951 - sentence_transformers.SentenceTransformer - INFO - __init__ - 197- Load pretrained SentenceTransformer: all-MiniLM-L6-v2
2024-08-30 20:33:29,952 - sentence_transformers.SentenceTransformer - INFO - __init__ - 189- Use pytorch device_name: cpu
2024-08-30 20:33:29,952 - sentence_transformers.SentenceTransformer - INFO - __init__ - 197- Load pretrained SentenceTransformer: all-MiniLM-L6-v2
2024-08-30 20:34:10,117 - sentence_transformers.SentenceTransformer - INFO - __init__ - 189- Use pytorch device_name: cpu
2024-08-30 20:34:10,118 - sentence_transformers.SentenceTransformer - INFO - __init__ - 197- Load pretrained SentenceTransformer: all-MiniLM-L6-v2
2024-08-30 20:34:31,808 - sentence_transformers.SentenceTransformer - INFO - __init__ - 189- Use pytorch device_name: cpu
2024-08-30 20:34:31,808 - sentence_transformers.SentenceTransformer - INFO - __init__ - 197- Load pretrained SentenceTransformer: all-MiniLM-L6-v2
2024-08-30 20:40:20,223 - sentence_transformers.SentenceTransformer - INFO - __init__ - 189- Use pytorch device_name: cpu
2024-08-30 20:40:20,223 - sentence_transformers.SentenceTransformer - INFO - __init__ - 197- Load pretrained SentenceTransformer: all-MiniLM-L6-v2
2024-08-30 20:40:38,232 - sentence_transformers.SentenceTransformer - INFO - __init__ - 189- Use pytorch device_name: cpu
2024-08-30 20:40:38,232 - sentence_transformers.SentenceTransformer - INFO - __init__ - 197- Load pretrained SentenceTransformer: all-MiniLM-L6-v2
2024-08-31 21:43:04,768 - backoff - ERROR - _log_giveup - 120- Giving up send_request(...) after 4 tries (requests.exceptions.ConnectionError: HTTPSConnectionPool(host='us.i.posthog.com', port=443): Max retries exceeded with url: /batch/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000253EDC68F50>: Failed to resolve 'us.i.posthog.com' ([Errno 11001] getaddrinfo failed)")))
2024-08-31 21:43:05,278 - backoff - INFO - _log_backoff - 105- Backing off send_request(...) for 0.1s (requests.exceptions.ConnectionError: HTTPSConnectionPool(host='us.i.posthog.com', port=443): Max retries exceeded with url: /batch/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000253EDC6A600>: Failed to resolve 'us.i.posthog.com' ([Errno 11001] getaddrinfo failed)")))
2024-08-31 21:43:05,397 - backoff - INFO - _log_backoff - 105- Backing off send_request(...) for 1.0s (requests.exceptions.ConnectionError: HTTPSConnectionPool(host='us.i.posthog.com', port=443): Max retries exceeded with url: /batch/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000253EDC6AF60>: Failed to resolve 'us.i.posthog.com' ([Errno 11001] getaddrinfo failed)")))
2024-08-31 21:43:06,448 - backoff - INFO - _log_backoff - 105- Backing off send_request(...) for 3.6s (requests.exceptions.ConnectionError: HTTPSConnectionPool(host='us.i.posthog.com', port=443): Max retries exceeded with url: /batch/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000253EDC68B00>: Failed to resolve 'us.i.posthog.com' ([Errno 11001] getaddrinfo failed)")))
2024-08-31 21:43:10,063 - backoff - ERROR - _log_giveup - 120- Giving up send_request(...) after 4 tries (requests.exceptions.ConnectionError: HTTPSConnectionPool(host='us.i.posthog.com', port=443): Max retries exceeded with url: /batch/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000253EDC68680>: Failed to resolve 'us.i.posthog.com' ([Errno 11001] getaddrinfo failed)")))
2024-08-31 21:44:51,189 - backoff - INFO - _log_backoff - 105- Backing off send_request(...) for 0.4s (requests.exceptions.ConnectionError: HTTPSConnectionPool(host='us.i.posthog.com', port=443): Max retries exceeded with url: /batch/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000204597244A0>: Failed to resolve 'us.i.posthog.com' ([Errno 11001] getaddrinfo failed)")))
2024-08-31 21:44:51,587 - backoff - INFO - _log_backoff - 105- Backing off send_request(...) for 2.0s (requests.exceptions.ConnectionError: HTTPSConnectionPool(host='us.i.posthog.com', port=443): Max retries exceeded with url: /batch/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000020459706570>: Failed to resolve 'us.i.posthog.com' ([Errno 11001] getaddrinfo failed)")))
2024-08-31 21:44:53,570 - backoff - INFO - _log_backoff - 105- Backing off send_request(...) for 2.7s (requests.exceptions.ConnectionError: HTTPSConnectionPool(host='us.i.posthog.com', port=443): Max retries exceeded with url: /batch/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000020459706270>: Failed to resolve 'us.i.posthog.com' ([Errno 11001] getaddrinfo failed)")))
2024-08-31 21:44:56,275 - backoff - ERROR - _log_giveup - 120- Giving up send_request(...) after 4 tries (requests.exceptions.ConnectionError: HTTPSConnectionPool(host='us.i.posthog.com', port=443): Max retries exceeded with url: /batch/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000020459705E80>: Failed to resolve 'us.i.posthog.com' ([Errno 11001] getaddrinfo failed)")))
2024-08-31 21:45:15,459 - backoff - INFO - _log_backoff - 105- Backing off send_request(...) for 0.5s (requests.exceptions.ConnectionError: HTTPSConnectionPool(host='us.i.posthog.com', port=443): Max retries exceeded with url: /batch/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F9D0723E90>: Failed to resolve 'us.i.posthog.com' ([Errno 11001] getaddrinfo failed)")))
2024-08-31 21:45:15,942 - backoff - INFO - _log_backoff - 105- Backing off send_request(...) for 1.5s (requests.exceptions.ConnectionError: HTTPSConnectionPool(host='us.i.posthog.com', port=443): Max retries exceeded with url: /batch/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F9D075A270>: Failed to resolve 'us.i.posthog.com' ([Errno 11001] getaddrinfo failed)")))
2024-08-31 21:45:17,478 - backoff - INFO - _log_backoff - 105- Backing off send_request(...) for 1.2s (requests.exceptions.ConnectionError: HTTPSConnectionPool(host='us.i.posthog.com', port=443): Max retries exceeded with url: /batch/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F9D075A5A0>: Failed to resolve 'us.i.posthog.com' ([Errno 11001] getaddrinfo failed)")))
2024-08-31 21:45:18,647 - backoff - ERROR - _log_giveup - 120- Giving up send_request(...) after 4 tries (requests.exceptions.ConnectionError: HTTPSConnectionPool(host='us.i.posthog.com', port=443): Max retries exceeded with url: /batch/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F9D075A9C0>: Failed to resolve 'us.i.posthog.com' ([Errno 11001] getaddrinfo failed)")))
2024-08-31 21:46:23,308 - backoff - INFO - _log_backoff - 105- Backing off send_request(...) for 0.8s (requests.exceptions.ConnectionError: HTTPSConnectionPool(host='us.i.posthog.com', port=443): Max retries exceeded with url: /batch/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000259F3DB08F0>: Failed to resolve 'us.i.posthog.com' ([Errno 11001] getaddrinfo failed)")))
2024-08-31 21:46:24,147 - backoff - INFO - _log_backoff - 105- Backing off send_request(...) for 3.3s (requests.exceptions.ConnectionError: HTTPSConnectionPool(host='us.i.posthog.com', port=443): Max retries exceeded with url: /batch/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000259F3DB2300>: Failed to resolve 'us.i.posthog.com' ([Errno 11001] getaddrinfo failed)")))
2024-08-31 21:46:27,479 - backoff - ERROR - _log_giveup - 120- Giving up send_request(...) after 4 tries (requests.exceptions.ConnectionError: HTTPSConnectionPool(host='us.i.posthog.com', port=443): Max retries exceeded with url: /batch/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000259F3DB2780>: Failed to resolve 'us.i.posthog.com' ([Errno 11001] getaddrinfo failed)")))
2024-08-31 21:46:46,638 - backoff - INFO - _log_backoff - 105- Backing off send_request(...) for 0.9s (requests.exceptions.ConnectionError: HTTPSConnectionPool(host='us.i.posthog.com', port=443): Max retries exceeded with url: /batch/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001D033023E60>: Failed to resolve 'us.i.posthog.com' ([Errno 11001] getaddrinfo failed)")))
2024-08-31 21:46:47,517 - backoff - INFO - _log_backoff - 105- Backing off send_request(...) for 1.6s (requests.exceptions.ConnectionError: HTTPSConnectionPool(host='us.i.posthog.com', port=443): Max retries exceeded with url: /batch/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001D033059C10>: Failed to resolve 'us.i.posthog.com' ([Errno 11001] getaddrinfo failed)")))
2024-08-31 21:46:49,125 - backoff - INFO - _log_backoff - 105- Backing off send_request(...) for 0.3s (requests.exceptions.ConnectionError: HTTPSConnectionPool(host='us.i.posthog.com', port=443): Max retries exceeded with url: /batch/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001D033059F10>: Failed to resolve 'us.i.posthog.com' ([Errno 11001] getaddrinfo failed)")))
2024-08-31 21:46:49,417 - backoff - ERROR - _log_giveup - 120- Giving up send_request(...) after 4 tries (requests.exceptions.ConnectionError: HTTPSConnectionPool(host='us.i.posthog.com', port=443): Max retries exceeded with url: /batch/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001D03305A300>: Failed to resolve 'us.i.posthog.com' ([Errno 11001] getaddrinfo failed)")))
2024-08-31 21:47:31,959 - backoff - INFO - _log_backoff - 105- Backing off send_request(...) for 2.8s (requests.exceptions.ConnectionError: HTTPSConnectionPool(host='us.i.posthog.com', port=443): Max retries exceeded with url: /batch/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000022620F3B980>: Failed to resolve 'us.i.posthog.com' ([Errno 11001] getaddrinfo failed)")))
2024-08-31 21:47:34,751 - backoff - ERROR - _log_giveup - 120- Giving up send_request(...) after 4 tries (requests.exceptions.ConnectionError: HTTPSConnectionPool(host='us.i.posthog.com', port=443): Max retries exceeded with url: /batch/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000022620F61B80>: Failed to resolve 'us.i.posthog.com' ([Errno 11001] getaddrinfo failed)")))
2024-08-31 21:47:35,268 - backoff - INFO - _log_backoff - 105- Backing off send_request(...) for 0.2s (requests.exceptions.ConnectionError: HTTPSConnectionPool(host='us.i.posthog.com', port=443): Max retries exceeded with url: /batch/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000022620F60B90>: Failed to resolve 'us.i.posthog.com' ([Errno 11001] getaddrinfo failed)")))
2024-08-31 21:47:35,493 - backoff - INFO - _log_backoff - 105- Backing off send_request(...) for 1.2s (requests.exceptions.ConnectionError: HTTPSConnectionPool(host='us.i.posthog.com', port=443): Max retries exceeded with url: /batch/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000022620F63110>: Failed to resolve 'us.i.posthog.com' ([Errno 11001] getaddrinfo failed)")))
2024-08-31 21:47:36,699 - backoff - INFO - _log_backoff - 105- Backing off send_request(...) for 0.3s (requests.exceptions.ConnectionError: HTTPSConnectionPool(host='us.i.posthog.com', port=443): Max retries exceeded with url: /batch/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000022620F63530>: Failed to resolve 'us.i.posthog.com' ([Errno 11001] getaddrinfo failed)")))
2024-08-31 21:47:37,013 - backoff - ERROR - _log_giveup - 120- Giving up send_request(...) after 4 tries (requests.exceptions.ConnectionError: HTTPSConnectionPool(host='us.i.posthog.com', port=443): Max retries exceeded with url: /batch/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000022620F63920>: Failed to resolve 'us.i.posthog.com' ([Errno 11001] getaddrinfo failed)")))
2024-09-02 20:01:21,771 - backoff - INFO - _log_backoff - 105- Backing off send_request(...) for 0.7s (requests.exceptions.ConnectionError: HTTPSConnectionPool(host='us.i.posthog.com', port=443): Max retries exceeded with url: /batch/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000264B4260560>: Failed to resolve 'us.i.posthog.com' ([Errno 11001] getaddrinfo failed)")))
2024-09-02 20:01:22,473 - backoff - INFO - _log_backoff - 105- Backing off send_request(...) for 0.5s (requests.exceptions.ConnectionError: HTTPSConnectionPool(host='us.i.posthog.com', port=443): Max retries exceeded with url: /batch/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000264B4261730>: Failed to resolve 'us.i.posthog.com' ([Errno 11001] getaddrinfo failed)")))
2024-09-02 20:01:22,974 - backoff - INFO - _log_backoff - 105- Backing off send_request(...) for 2.8s (requests.exceptions.ConnectionError: HTTPSConnectionPool(host='us.i.posthog.com', port=443): Max retries exceeded with url: /batch/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000264B4261B20>: Failed to resolve 'us.i.posthog.com' ([Errno 11001] getaddrinfo failed)")))
2024-09-02 20:01:25,801 - backoff - ERROR - _log_giveup - 120- Giving up send_request(...) after 4 tries (requests.exceptions.ConnectionError: HTTPSConnectionPool(host='us.i.posthog.com', port=443): Max retries exceeded with url: /batch/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000264B4261F70>: Failed to resolve 'us.i.posthog.com' ([Errno 11001] getaddrinfo failed)")))
2024-09-02 20:07:56,897 - sentence_transformers.SentenceTransformer - INFO - __init__ - 189- Use pytorch device_name: cpu
2024-09-02 20:07:56,898 - sentence_transformers.SentenceTransformer - INFO - __init__ - 197- Load pretrained SentenceTransformer: all-MiniLM-L6-v2
2024-09-02 20:08:02,243 - chromadb.segment.impl.vector.local_hnsw - WARNING - query_vectors - 138- Number of requested results 4 is greater than number of elements in index 3, updating n_results = 3
2024-09-02 20:35:01,499 - sentence_transformers.SentenceTransformer - INFO - __init__ - 189- Use pytorch device_name: cpu
2024-09-02 20:35:01,500 - sentence_transformers.SentenceTransformer - INFO - __init__ - 197- Load pretrained SentenceTransformer: all-MiniLM-L6-v2
2024-09-02 20:37:25,384 - sentence_transformers.SentenceTransformer - INFO - __init__ - 189- Use pytorch device_name: cpu
2024-09-02 20:37:25,384 - sentence_transformers.SentenceTransformer - INFO - __init__ - 197- Load pretrained SentenceTransformer: all-MiniLM-L6-v2
2024-09-02 20:39:11,447 - sentence_transformers.SentenceTransformer - INFO - __init__ - 189- Use pytorch device_name: cpu
2024-09-02 20:39:11,447 - sentence_transformers.SentenceTransformer - INFO - __init__ - 197- Load pretrained SentenceTransformer: all-MiniLM-L6-v2
2024-09-02 20:39:16,429 - sentence_transformers.SentenceTransformer - INFO - __init__ - 189- Use pytorch device_name: cpu
2024-09-02 20:39:16,429 - sentence_transformers.SentenceTransformer - INFO - __init__ - 197- Load pretrained SentenceTransformer: all-MiniLM-L6-v2
2024-09-02 20:41:00,240 - sentence_transformers.SentenceTransformer - INFO - __init__ - 189- Use pytorch device_name: cpu
2024-09-02 20:41:00,240 - sentence_transformers.SentenceTransformer - INFO - __init__ - 197- Load pretrained SentenceTransformer: all-MiniLM-L6-v2
2024-09-02 20:41:14,909 - sentence_transformers.SentenceTransformer - INFO - __init__ - 189- Use pytorch device_name: cpu
2024-09-02 20:41:14,909 - sentence_transformers.SentenceTransformer - INFO - __init__ - 197- Load pretrained SentenceTransformer: all-MiniLM-L6-v2
2024-09-02 20:45:38,594 - sentence_transformers.SentenceTransformer - INFO - __init__ - 189- Use pytorch device_name: cpu
2024-09-02 20:45:38,594 - sentence_transformers.SentenceTransformer - INFO - __init__ - 197- Load pretrained SentenceTransformer: all-MiniLM-L6-v2
2024-09-02 20:53:33,162 - sentence_transformers.SentenceTransformer - INFO - __init__ - 189- Use pytorch device_name: cpu
2024-09-02 20:53:33,162 - sentence_transformers.SentenceTransformer - INFO - __init__ - 197- Load pretrained SentenceTransformer: all-MiniLM-L6-v2
2024-09-02 20:58:47,234 - sentence_transformers.SentenceTransformer - INFO - __init__ - 189- Use pytorch device_name: cpu
2024-09-02 20:58:47,234 - sentence_transformers.SentenceTransformer - INFO - __init__ - 197- Load pretrained SentenceTransformer: all-MiniLM-L6-v2
2024-09-02 20:59:01,347 - sentence_transformers.SentenceTransformer - INFO - __init__ - 189- Use pytorch device_name: cpu
2024-09-02 20:59:01,347 - sentence_transformers.SentenceTransformer - INFO - __init__ - 197- Load pretrained SentenceTransformer: all-MiniLM-L6-v2
2024-09-02 20:59:17,012 - chromadb.segment.impl.vector.local_hnsw - WARNING - query_vectors - 138- Number of requested results 4 is greater than number of elements in index 3, updating n_results = 3
